### ISSUE TITLE
Arguments ndraws and nclusters in project()

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#85] opened 2021-03-18 12:21 UTC
There seems to be a mismatch between the documentation and the behavior of arguments `ndraws` and `nclusters` in `project()`: In the reprex below, `.get_refdist()` clusters the posterior draws (into 400 clusters) since inside of `project()`, `nclusters <- ndraws` is used in that case. In contrast, the documentation suggests that if---as per default---`ndraws` is specified and `nclusters` not, no clustering is performed. (The current solution in that case---namely to "thin" the posterior draws and not to subsample them---is another issue which should be discussed separately.)

```r
# Source: https://github.com/stan-dev/projpred/blob/master/README.md

library(projpred)
library(rstanarm)
options(mc.cores = parallel::detectCores(logical = FALSE))

# Gaussian and Binomial examples from the glmnet-package
data('df_gaussian', package = 'projpred')

mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
# fit the full model with a sparsifying prior
fit <- stan_glm(y ~ V1 + V2 + V3 + V4 + V5,
                family = gaussian(),
                data = mydat,
                prior = hs(df = 1, global_scale=0.01), seed = 1140350788)

myproj <- project(fit,
                  solution_terms = c("V3", "V2"))
```

**Comment by AlejandroCatalina** [comment] 2021-03-18 12:37
I'm sorry I'm failing to see where that's said in the documentation of `project` or how that example is relevant to this? Can you point out the misleading documentation more explicitly so I can see it?

**Comment by fweber144** [comment] 2021-03-18 14:10
It's probably not only a mismatch between documentation and implementation, but a bug.

The documentation for `ndraws` says:

> Number of posterior draws to be projected. [...]

If the current implementation was correct, then it should perhaps say something like "Number of clusters of posterior draws to be used in the projection. [...]" But that would overlap with `nclusters`---which in turn shows that it's probably a bug.

**Comment by AlejandroCatalina** [comment] 2021-03-22 11:12
Well, I'm going to clarify this. It is not a bug but documentation can be clearer. 

What we mean is that if `nclusters` is null we use as many clusters as draws. But documentation for `ndraws` is correct in the sense that we do project `ndraws` posterior draws. So we can clarify the default behaviour.

**Comment by fweber144** [comment] 2021-03-22 12:37
> What we mean is that if `nclusters` is null we use as many clusters as draws.

Really? I thought that if `nclusters` is null and `ndraws` is specified, then the posterior draws are not clustered, but thinned (or subsampled, see #86). And if `nclusters` is null and `ndraws` is not specified (i.e. also null), then 20 clusters are used.

**Comment by AlejandroCatalina** [comment] 2021-03-22 12:42
We have a `parse_args_varsel` function that sets `nclusters` to `ndraws` if `nclusters` is null in varsel.R:L307 I believe (develop branch).

**Comment by fweber144** [comment] 2021-03-22 16:31
That's right and that might be the problem. I think we are in line https://github.com/stan-dev/projpred/blob/0cabd73548eec32e9b675f15cd39d377a40f180a/R/varsel.R#L301 here (and line https://github.com/stan-dev/projpred/blob/0cabd73548eec32e9b675f15cd39d377a40f180a/R/varsel.R#L314 for the `_pred` analogon). I think that the `nclusters <- ` assignment (and the `nclusters_pred <- ` assignment, respectively) needs to be removed. As soon as I have the time, I'll check that (and also the other assignments). The relevant changes seem to have been introduced by commit 80b10dc.

**Comment by AlejandroCatalina** [comment] 2021-03-22 16:33
This was introduced on purpose. I clarified the documentation regarding the interaction of these arguments but we can probably improve that.

Best, Alejandro

**Comment by AlejandroCatalina** [comment] 2021-04-09 11:12
Latest develop should be better but there is some work to do still. I'll close this for now as I think it's resolved in a way.

**Closed by AlejandroCatalina** 2021-04-09 11:12 UTC

**Comment by fweber144** [comment] 2021-04-09 13:37
There is commit 37c623fb7bce42866e95630714c5b8a87721754d on branch `workflow` but it seems like it hasn't made it yet into `develop`. Or are you talking of another commit?
